#!/bin/bash
# iextract - download and extract archives

main() {
  wget $1 && ex $(basename $1) && rm $(basename $1) && echo Extracted. || echo "Error!"
}

# ex - archive extractor - usage: ex <file>
ex () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.txz)       tar xJf $1   ;;
      *.tar.xz)    tar xJf $1   ;;
      *.xz)        xz -d $1     ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tbz)       tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.tsh)       ./$1         ;;
      *.sh)        ./$1         ;;
      *.run)       sudo ./$1    ;;
      *.tar.*)     tar xaf $1   ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

main
