#!/bin/bash
# safe rm
# Creates a sort of "recycle bin" that can be used to 'rm' files without
# permanently deleting them.
TrashDir=~/.Trash
mfile="$TrashDir/$UID/.saferm_metadata"
d=$(date +%d)
[[ -d "$TrashDir/$UID/$d" ]] || mkdir -p "$TrashDir/$UID/$d"
for file in "$@"; do
  if (echo $file | grep -q '^-.*'); then 
    if (echo $file | grep -q 'r'); then
      rmdirs=true
    fi
    continue
  else
    if [[ -d "$file" ]]; then
      [[ "$rmdirs" != "true" ]] && echo "cannot remove \`$file': Is a directory" && continue
    fi
    if [[ -e "$TrashDir/$UID/$d/$file" ]]; then
      ts="$(date +%N)"
      mv -f "$file" "$TrashDir/$UID/$d/$file.$ts" && echo "$d/$file.$ts===$file" >> "$mfile" || echo "ERROR!"
      mv -f "$TrashDir/$UID/$d/$file" "$TrashDir/$UID/$d/$file.orig$d" && sed -i "s@$d/\($file$\)@$d/\1.orig$d===\1@" "$mfile" || echo "ERROR!"
    else
      mv -f "$file" "$TrashDir/$UID/$d" && echo "$d/$file" >> "$mfile" || echo "ERROR!"
    fi
  fi
done
